# version: '2'

services:

  database:
    build:
      context: ./database
      no_cache: true
    networks:
      - lab3network

  worker:
    build:
      context: ./worker
      no_cache: true
    depends_on:
      - database
      - rabbitmq
      - web-server
    networks:
      - lab3network

  rabbitmq:
    image: rabbitmq:3-management  # RabbitMQ с веб-интерфейсом
    ports:
      - "5672:5672"  # Порт для работы с брокером
      - "15672:15672"  # Порт для управления через веб-интерфейс
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - lab3network

  web-server:
    build:
      context: ./web-server
      no_cache: true
    depends_on:
      - rabbitmq
    networks:
      - lab3network

  nginx:
    image: nginx
    hostname: nginx
    domainname: nginx
    volumes:
      - /home/luki/Study/PARVPO/PARVPO/Parvpo-lab3-drn/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - /home/luki/Study/PARVPO/PARVPO/Parvpo-lab3-drn/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:5000"
    depends_on:
      - web-server
    networks:
      - lab3network

networks:
  lab3network: