# version: '2'

services:

  database:
    build:
      context: ./database
      no_cache: true
    networks:
      - lab3network

  worker:
    build:
      context: ./worker
      no_cache: true
    depends_on:
      - database
    networks:
      - lab3network

  web-server:
    build:
      context: ./web-server
      no_cache: true
    ports:
      - "5000:5000"
      - "8080:8080"
    depends_on:
      - worker
    networks:
      - lab3network

networks:
  lab3network: